# Generated by Django 4.2.5 on 2023-12-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=1, verbose_name='性别')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('admin', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为管理员')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='电话')),
                ('Account', models.CharField(max_length=32, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('Sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=1, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicensePlate', models.CharField(max_length=20, verbose_name='车牌号')),
                ('Name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('VehicleColor', models.CharField(max_length=20, verbose_name='车牌颜色')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicensePlate', models.CharField(max_length=30, verbose_name='车牌号')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='进入时间')),
                ('created_out', models.DateTimeField(blank=True, null=True, verbose_name='外出时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admin', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('status', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已支付')),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plate', verbose_name='车牌号')),
            ],
        ),
    ]
